version: "3"
services:
    backend:
        image: amanbarar/backend-image:${BUILD_ID}
        build:
            dockerfile: Dockerfile.node
            context: ./backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=development
            - PORT=5000
            - OPENAI_API_KEY=$OPENAI_API_KEY
            - FRONTEND=http://frontend:3000
    frontend:
        image: amanbarar/frontend-image:${BUILD_ID}
        stdin_open: true
        build:
            dockerfile: Dockerfile.reactUI
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
        ports:
            - "3000:3000"
        environment:
          - BACKEND_URL=http://backend:5000
          - DOCKER_ENV=true

